<?php

return [
    'main/index' => 'Main/index',
    'main/update' => 'Main/update',
    'main/delete' => 'Main/delete',
    'about/index' => 'About/index',
    'gallery' => 'Gallery/view',
    'gallery/index' => 'Gallery/view',
    'admin/gallery/index' => 'Admin/gallery/index',
    'admin/gallery/update' => 'Admin/gallery/update',
    'admin/gallery/create' => 'Admin/gallery/create',
    'admin/gallery/delete' => 'Admin/gallery/delete',
    'admin/post/index' => 'Admin/post/index',
    'admin/post/update' => 'Admin/post/update',
    'admin/post/create' => 'Admin/post/create',
    'admin/post/delete' => 'Admin/post/delete',
    'admin/postcategory/index' => 'Admin/postcategory/index',
    'admin/postcategory/update' => 'Admin/postcategory/update',
    'admin/postcategory/create' => 'Admin/postcategory/create',
    'admin/postcategory/delete' => 'Admin/postcategory/delete',
    'admin/gallerycategory/index' => 'Admin/gallerycategory/index',
    'admin/gallerycategory/update' => 'Admin/gallerycategory/update',
    'admin/gallerycategory/create' => 'Admin/gallerycategory/create',
    'admin/gallerycategory/delete' => 'Admin/gallerycategory/delete',
    'admin/user/index' => 'Admin/user/index',
    'admin/user/update' => 'Admin/user/update',
    'admin/user/create' => 'Admin/user/create',
    'admin/user/delete' => 'Admin/user/delete',
    'admin/main/index' => 'Admin/main/index',
    'admin/dashboard/index' => 'Admin/Dashboard/index',
    'admin/error/index' => 'Admin/error/index',
    'error/index' => 'Error/index',
];